In [1]:
import matplotlib
import pandas as pd
import seaborn as sns
import numpy as np
import random

In [2]:
# Load the data
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab2%20-%20bootstrap/customers.csv')
customers = df.values.T[1]
print(customers)

[ 2.  8. 20. 13.  5.  9. 10.  8. 22. 10.  2.  4.  7.  9.]


In [3]:
# Checking the notes from the lecture, create here your own bootstrap function:
# 1. Sample from the input array x to create an array of samples of shape (n_bootstraps, sample_size)
# Hint: Check the function random.choice() on Numpy
# 2. Calculate and save the mean of the array (this is "data_mean" that is returned by the function)
# 3. Calculate the mean from each bootstrap (i.e., row) and store it.
# (This should be an array of n_bootstraps values)
# 4. Calculate the lower and upper bounds for a 95% CI (hint: check the percentile function on Numpy)
# 5. Return data_mean, and the lower and upper bounds of your interval
def bootstrap_mean(x, sample_size, n_bootstraps):
  #Create an empty 2d list
  boot_array = [[random.choice(x) for i in range(sample_size)] for j in range(n_bootstraps)]
  #2. Calculate and save the mean of the array (this is "data_mean" that is returned by the function)
  for each_boots in boot_array:
    boot_mean_array = np.mean(each_boots)
  data_mean = np.mean(boot_mean_array)
  # 3. Calculate the mean from each bootstrap (i.e., row) and store it.
  #Fill the list 
  #Calculate the mean of each boot straps

  # 4. Calculate the lower and upper bounds for a 95% CI (hint: check the percentile function on Numpy)
  upper = np.percentile(boot_mean_array, 100 - ((100-ci)/2), axis =0) 
  lower = np.percentile(boot_mean_array, (100-ci)/2, axis =0) 
  return data_mean, lower, upper


	#return data_mean, lower, upper
#boot = bootstrap_mean(data, data.shape[0], 10)
#print(bootstrap_mean(data, data.shape[0], 10))

In [4]:
# Checking the notes from the lecture, create here your own bootstrap function:
# 1. Sample from the input array x to create an array of samples of shape (n_bootstraps, sample_size)
# Hint: Check the function random.choice() on Numpy
# 2. Calculate and save the mean of the array (this is "data_mean" that is returned by the function)
# 3. Calculate the mean from each bootstrap (i.e., row) and store it.
# (This should be an array of n_bootstraps values)
# 4. Calculate the lower and upper bounds for a 95% CI (hint: check the percentile function on Numpy)
# 5. Return data_mean, and the lower and upper bounds of your interval
def bootstrap_mean_ci(x, sample_size, n_bootstraps,ci):
  #Create an empty 2d list
  boot_array = [[random.choice(x) for i in range(sample_size)] for j in range(n_bootstraps)]
  #for()
  #2. Calculate and save the mean of the array (this is "data_mean" that is returned by the function)
  boot_mean_array = []
  for each_boots in boot_array:
    boot_mean_array.append(np.mean(each_boots)) 
  data_mean = np.mean(boot_mean_array)
  # 3. Calculate the mean from each bootstrap (i.e., row) and store it.
  #Fill the list 
  #Calculate the mean of each boot straps

  # 4. Calculate the lower and upper bounds for a 95% CI (hint: check the percentile function on Numpy)
  upper = np.percentile(boot_mean_array, 100 - ((100-ci)/2), axis =0) 
  lower = np.percentile(boot_mean_array, (100-ci)/2, axis =0) 
  

  return data_mean, lower, upper


	#return data_mean, lower, upper
#boot = bootstrap_mean(data, data.shape[0], 10)
#print(bootstrap_mean(data, data.shape[0], 10))

In [5]:
#df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab2%20-%20bootstrap/customers.csv')
#customers dataset
bootstrap_mean_ci(customers, customers.shape[0], 10000 ,95)

(9.213907142857142, 6.428571428571429, 12.357142857142858)

In [6]:
fleet_data = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab2%20-%20bootstrap/vehicles.csv')

In [7]:
current_fleet = fleet_data['Current fleet']
print(current_fleet)

0      18
1      15
2      18
3      16
4      17
       ..
244    27
245    27
246    32
247    28
248    31
Name: Current fleet, Length: 249, dtype: int64


In [8]:
result_current_fleet = bootstrap_mean_ci(current_fleet, current_fleet.shape[0], 10000  ,92)
print(np.round(result_current_fleet,2))

[20.14 19.44 20.85]


In [9]:
result_current_fleet = bootstrap_mean_ci(current_fleet, current_fleet.shape[0], 10000  ,80)
print(np.round(result_current_fleet,2))

[20.14 19.63 20.65]


In [10]:
# Checking the notes from the lecture, create here your own bootstrap function:
# 1. Sample from the input array x to create an array of samples of shape (n_bootstraps, sample_size)
# Hint: Check the function random.choice() on Numpy
# 2. Calculate and save the mean of the array (this is "data_mean" that is returned by the function)
# 3. Calculate the mean from each bootstrap (i.e., row) and store it.
# (This should be an array of n_bootstraps values)
# 4. Calculate the lower and upper bounds for a 95% CI (hint: check the percentile function on Numpy)
# 5. Return data_mean, and the lower and upper bounds of your interval
def bootstrap_std_ci(x, sample_size, n_bootstraps,ci):
  #Create an empty 2d list
  boot_array = [[random.choice(x) for i in range(sample_size)] for j in range(n_bootstraps)]
  #2. Calculate and save the mean of the array (this is "data_mean" that is returned by the function)
  boot_std_array = []
  for each_boots in boot_array:
    boot_std_array.append(np.std(each_boots)) 
  data_std = np.mean(boot_std_array)
  # 3. Calculate the mean from each bootstrap (i.e., row) and store it.
  #Fill the list 
  #Calculate the mean of each boot straps

  # 4. Calculate the lower and upper bounds for a 95% CI (hint: check the percentile function on Numpy)
  upper = np.percentile(boot_std_array, 100 - ((100-ci)/2), axis =0) 
  lower = np.percentile(boot_std_array, (100-ci)/2, axis =0) 
  

  return data_std, lower, upper


	#return data_mean, lower, upper
#boot = bootstrap_mean(data, data.shape[0], 10)
#print(bootstrap_mean(data, data.shape[0], 10))

In [11]:
result_std_current_fleet = bootstrap_std_ci(current_fleet, current_fleet.shape[0], 10000   ,73)
print(np.round(result_std_current_fleet,2))

[6.38 6.05 6.69]


In [12]:
result_std_customers= bootstrap_std_ci(customers, customers.shape[0], 10000 ,85)
print(np.round(result_std_customers,2))

[5.35 3.26 6.95]


In [13]:
import math
new_fleet = fleet_data['New Fleet']
#delete Nan values in numpy array 
nan_array = np.isnan(new_fleet)
not_nan_array = ~ nan_array
filtered_new_fleet = new_fleet[not_nan_array]
print(filtered_new_fleet)

0     24.0
1     27.0
2     27.0
3     25.0
4     31.0
      ... 
74    34.0
75    38.0
76    32.0
77    38.0
78    32.0
Name: New Fleet, Length: 79, dtype: float64


In [14]:
result = bootstrap_mean_ci(filtered_new_fleet, filtered_new_fleet.shape[0], 10000,95)
print(np.round(result,2))


[30.48 29.13 31.84]


In [15]:
# <---INSERT YOUR CODE HERE--->
fleet_data = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab2%20-%20bootstrap/vehicles.csv')
fleet_data_values_old = fleet_data.values.T[0]
print(fleet_data.values.T[0])

[18. 15. 18. 16. 17. 15. 14. 14. 14. 15. 15. 14. 15. 14. 22. 18. 21. 21.
 10. 10. 11.  9. 28. 25. 19. 16. 17. 19. 18. 14. 14. 14. 14. 12. 13. 13.
 18. 22. 19. 18. 23. 26. 25. 20. 21. 13. 14. 15. 14. 17. 11. 13. 12. 13.
 15. 13. 13. 14. 22. 28. 13. 14. 13. 14. 15. 12. 13. 13. 14. 13. 12. 13.
 18. 16. 18. 18. 23. 11. 12. 13. 12. 18. 21. 19. 21. 15. 16. 15. 11. 20.
 21. 19. 15. 26. 25. 16. 16. 18. 16. 13. 14. 14. 14. 28. 19. 18. 15. 15.
 16. 15. 16. 14. 17. 16. 15. 18. 21. 20. 13. 23. 20. 23. 18. 19. 25. 26.
 18. 16. 16. 15. 22. 22. 24. 23. 29. 25. 20. 18. 19. 18. 27. 13. 17. 13.
 13. 13. 30. 26. 18. 17. 16. 15. 18. 21. 19. 19. 16. 16. 16. 16. 25. 26.
 31. 34. 36. 20. 19. 20. 19. 21. 20. 25. 21. 19. 21. 21. 19. 18. 19. 18.
 18. 18. 30. 31. 23. 24. 22. 20. 22. 20. 21. 17. 18. 17. 18. 17. 16. 19.
 19. 36. 27. 23. 24. 34. 35. 28. 29. 27. 34. 32. 28. 26. 24. 19. 28. 24.
 27. 27. 26. 24. 30. 39. 35. 34. 30. 22. 27. 20. 18. 28. 27. 34. 31. 29.
 27. 24. 23. 38. 36. 25. 38. 26. 22. 36. 27. 27. 32

In [16]:
fleet_data_values_new = fleet_data.values.T[1]
#delete Nan values in numpy array 
nan_array = np.isnan(fleet_data_values_new)
not_nan_array = ~ nan_array
fleet_data_values_new = fleet_data_values_new[not_nan_array]
print(fleet_data_values_new)

[24. 27. 27. 25. 31. 35. 24. 19. 28. 23. 27. 20. 22. 18. 20. 31. 32. 31.
 32. 24. 26. 29. 24. 24. 33. 33. 32. 28. 19. 32. 34. 26. 30. 22. 22. 33.
 39. 36. 28. 27. 21. 24. 30. 34. 32. 38. 37. 30. 31. 37. 32. 47. 41. 45.
 34. 33. 24. 32. 39. 35. 32. 37. 38. 34. 34. 32. 33. 32. 25. 24. 37. 31.
 36. 36. 34. 38. 32. 38. 32.]


In [17]:
mean_fleet_data_old = np.mean(fleet_data_values_old)
mean_fleet_data_new = np.mean(fleet_data_values_new)
print("Old data mean : ",  mean_fleet_data_old, ", new data mean: ", mean_fleet_data_new)
t_fleet_obs = np.round(mean_fleet_data_new - mean_fleet_data_old,3)
print("new data mean - old data mean = ", t_fleet_obs)

Old data mean :  20.14457831325301 , new data mean:  30.481012658227847
new data mean - old data mean =  10.336


In [18]:
concat = np.concatenate((fleet_data_values_old,fleet_data_values_new))

In [19]:
def permutation_vehicle(permutation_amount,concat):
    i = 0
    for vals in range(0,permutation_amount):
        perm = np.random.permutation(concat)
        pold = perm[:int(len(perm)/2)]
        pnew = perm[int(len(perm)/2):]
        t_perm = np.mean(pnew) - np.mean(pold)
        if t_perm > t_fleet_obs:
            i = i + 1
    return i

In [20]:
print(permutation_vehicle(30000,concat))

0


In [21]:
# The variables below represent the percentages of democratic votes in Pennsylvania and Ohio (one value for each state).
dem_share_PA = [60.08, 40.64, 36.07, 41.21, 31.04, 43.78, 44.08, 46.85, 44.71, 46.15, 63.10, 52.20, 43.18, 40.24, 39.92, 47.87, 37.77, 40.11, 49.85, 48.61, 38.62, 54.25, 34.84, 47.75, 43.82, 55.97, 58.23, 42.97, 42.38, 36.11, 37.53, 42.65, 50.96, 47.43, 56.24, 45.60, 46.39, 35.22, 48.56, 32.97, 57.88, 36.05, 37.72, 50.36, 32.12, 41.55, 54.66, 57.81, 54.58, 32.88, 54.37, 40.45, 47.61, 60.49, 43.11, 27.32, 44.03, 33.56, 37.26, 54.64, 43.12, 25.34, 49.79, 83.56, 40.09, 60.81, 49.81]
dem_share_OH = [56.94, 50.46, 65.99, 45.88, 42.23, 45.26, 57.01, 53.61, 59.10, 61.48, 43.43, 44.69, 54.59, 48.36, 45.89, 48.62, 43.92, 38.23, 28.79, 63.57, 38.07, 40.18, 43.05, 41.56, 42.49, 36.06, 52.76, 46.07, 39.43, 39.26, 47.47, 27.92, 38.01, 45.45, 29.07, 28.94, 51.28, 50.10, 39.84, 36.43, 35.71, 31.47, 47.01, 40.10, 48.76, 31.56, 39.86, 45.31, 35.47, 51.38, 46.33, 48.73, 41.77, 41.32, 48.46, 53.14, 34.01, 54.74, 40.67, 38.96, 46.29, 38.25, 6.80, 31.75, 46.33, 44.90, 33.57, 38.10, 39.67, 40.47, 49.44, 37.62, 36.71, 46.73, 42.20, 53.16, 52.40, 58.36, 68.02, 38.53, 34.58, 69.64, 60.50, 53.53, 36.54, 49.58, 41.97, 38.11]

In [22]:
print(dem_share_PA)

[60.08, 40.64, 36.07, 41.21, 31.04, 43.78, 44.08, 46.85, 44.71, 46.15, 63.1, 52.2, 43.18, 40.24, 39.92, 47.87, 37.77, 40.11, 49.85, 48.61, 38.62, 54.25, 34.84, 47.75, 43.82, 55.97, 58.23, 42.97, 42.38, 36.11, 37.53, 42.65, 50.96, 47.43, 56.24, 45.6, 46.39, 35.22, 48.56, 32.97, 57.88, 36.05, 37.72, 50.36, 32.12, 41.55, 54.66, 57.81, 54.58, 32.88, 54.37, 40.45, 47.61, 60.49, 43.11, 27.32, 44.03, 33.56, 37.26, 54.64, 43.12, 25.34, 49.79, 83.56, 40.09, 60.81, 49.81]


In [23]:
print(dem_share_OH)

[56.94, 50.46, 65.99, 45.88, 42.23, 45.26, 57.01, 53.61, 59.1, 61.48, 43.43, 44.69, 54.59, 48.36, 45.89, 48.62, 43.92, 38.23, 28.79, 63.57, 38.07, 40.18, 43.05, 41.56, 42.49, 36.06, 52.76, 46.07, 39.43, 39.26, 47.47, 27.92, 38.01, 45.45, 29.07, 28.94, 51.28, 50.1, 39.84, 36.43, 35.71, 31.47, 47.01, 40.1, 48.76, 31.56, 39.86, 45.31, 35.47, 51.38, 46.33, 48.73, 41.77, 41.32, 48.46, 53.14, 34.01, 54.74, 40.67, 38.96, 46.29, 38.25, 6.8, 31.75, 46.33, 44.9, 33.57, 38.1, 39.67, 40.47, 49.44, 37.62, 36.71, 46.73, 42.2, 53.16, 52.4, 58.36, 68.02, 38.53, 34.58, 69.64, 60.5, 53.53, 36.54, 49.58, 41.97, 38.11]


In [24]:
print("Amount of values in PA votes array: " , len(dem_share_PA))
print("Amount of values in OH votes array: " , len(dem_share_OH))

Amount of values in PA votes array:  67
Amount of values in OH votes array:  88


In [25]:
np.round(bootstrap_mean_ci(dem_share_OH, len(dem_share_OH), 25000  ,90),2)

array([44.32, 42.62, 46.06])

In [26]:
np.round(bootstrap_mean_ci(dem_share_PA, len(dem_share_PA), 25000  ,90),2)

array([45.48, 43.56, 47.49])

In [27]:
mean_hare_OH = np.mean(dem_share_OH)
mean_hare_PA = np.mean(dem_share_PA)
print("Ohio data mean : ",  mean_hare_OH, ", Pennsylvania mean: ", mean_hare_PA)
t_fleet_obs = np.round(mean_hare_OH - mean_hare_PA,3)
if(t_fleet_obs < -1):
    t_fleet_obs *= -1
    
print("new data mean - old data mean = ", t_fleet_obs)
concat = np.concatenate((dem_share_OH,dem_share_PA))

Ohio data mean :  44.31818181818182 , Pennsylvania mean:  45.476417910447765
new data mean - old data mean =  1.158


In [28]:
def permutation_vehicle(permutation_amount,concat):
    i = 0
    for vals in range(0,permutation_amount):
        perm = np.random.permutation(concat)
        pold = perm[:int(len(perm)/2)]
        pnew = perm[int(len(perm)/2):]
        t_perm = np.mean(pnew) - np.mean(pold)
        if t_perm > t_fleet_obs:
            i = i + 1
    return i

In [29]:
print(np.round(permutation_vehicle(20000 ,concat)/20000,2))

0.23
